modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/infernalstudios/Summoner-Scrolls/issues"
license = "MIT (Code); ARR (Assets)"

[[mods]]
modId = "summonerscrolls"
version = "${version}"
displayName = "Summoner Scrolls"
authors = '''
Nekomaster1000, Deadlydiamond98, Lyof, StevenPlayzz, Jonah_Fuses
'''
description = '''
Bringing more Magic into Minecraft via summons!
'''
logoFile = "icon.png"

[[dependencies.summonerscrolls]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.summonerscrolls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"